### ISSUE TITLE
import error while trying to train or evaluate

### ISSUE THREAD

**Issue by aalex1945** [reactive-systems/ml2#2]
I followed README and installed the ml2 from the source (pip install -e .[dev]). I've also confirmed docker running but when I ran ```python -m ml2.experiment.run configs/ltl-syn/neurips21/ht.json``` in cmd there was error:
INFO:matplotlib.font_manager:Failed to extract font properties from C:\Windows\Fonts\FZShuSong-Z01.ttf: In FT2Font: Can not load face (unknown file format; error code 0x2)
INFO:matplotlib.font_manager:generated new fontManager
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\ml2\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "E:\ProgramData\Anaconda3\envs\ml2\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "D:\Pros\LTL\LTL_Synthesis\ml2-main\ml2\experiment\__init__.py", line 1, in <module>
    from .experiment import Experiment
  File "D:\Pros\LTL\LTL_Synthesis\ml2-main\ml2\experiment\experiment.py", line 9, in <module>
    from ..pipelines import EvalTask
ImportError: cannot import name 'EvalTask' from 'ml2.pipelines' (D:\Pros\LTL\LTL_Synthesis\ml2-main\ml2\pipelines\__init__.py)

**Comment by aalex1945** [comment]
I used python 3.8 and ```pip install -e .[full]``` to build the environment. All finished, I run command ```python -m ml2.experiment.run configs/ltl-syn/neurips21/ht.json``` only to find the error message:
INFO:datasets:PyTorch version 2.1.2 available.
INFO:datasets:TensorFlow version 2.13.0 available.
Traceback (most recent call last):
  File "E:\ProgramData\Anaconda3\envs\ml2\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "E:\ProgramData\Anaconda3\envs\ml2\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "D:\Pros\LTL\LTL_Synthesis\ml2-main\ml2\__init__.py", line 27, in <module>
    from . import experiment, pipelines, tokenizers, train
  File "D:\Pros\LTL\LTL_Synthesis\ml2-main\ml2\experiment\__init__.py", line 1, in <module>
    from .experiment import Experiment
  File "D:\Pros\LTL\LTL_Synthesis\ml2-main\ml2\experiment\experiment.py", line 11, in <module>
    from ..train import Trainer
  File "D:\Pros\LTL\LTL_Synthesis\ml2-main\ml2\train\__init__.py", line 6, in <module>
    from .keras_trainer import KerasTrainer
  File "D:\Pros\LTL\LTL_Synthesis\ml2-main\ml2\train\keras_trainer.py", line 12, in <module>
    from wandb.keras import WandbMetricsLogger
ModuleNotFoundError: No module named 'wandb.keras'

What should I do to make all pack versions meet?

**Comment by aalex1945** [comment]
Well, I installed it with ```pip install ml2``` in a new environment and found the same error message.
